spring.application.name=ejercicio10

spring.datasource.url=jdbc:postgresql://dpg-d8ic186q1p3s73eibtf0-a.oregon-postgres.render.com:5432/bd_prog4_torres?sslmode=require
spring.datasource.username=bd_prog4_torres_user
spring.datasource.password=NIky1ocoYOBcO1RmdUq84cZNstsIsQ9j
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
